# Generated by Django 6.0.2 on 2026-02-25 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                db_index=True,
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["user", "status", "priority", "created_at"],
                name="idx_user_status_priority_created",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["user", "due_date"], name="idx_user_due_date"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["user", "title"], name="idx_user_title"),
        ),
    ]
