# Generated by Django 6.0.2 on 2026-02-25 08:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_task_due_date_alter_task_priority_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="task",
            new_name="idx_user_stat_prio_created",
            old_name="idx_user_status_priority_created",
        ),
    ]
